config/routes.rb
Rails.application.routes.draw do
  get 'card_game/war'

  get 'static_pages/portfolio'
  get 'static_pages/coming_soon'
  get 'static_pages/contact'
  get 'static_pages/resume'
    get 'static_pages/home'

  devise_for :users
  # root 'contacts#index'
  root 'static_pages#home'
  get 'users/new'
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: { minimum: 5 }
  validates :address, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :phone, presence: true, length: { maximum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contacts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/card_game_controller.rb
class CardGameController < ApplicationController
  def war
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :find_contact, only: [:edit, :update, :show, :destroy]
  helper_method :sort_column, :sort_direction

  def index
    if current_user.nil?
      @contacts = []
    else
      @contacts = current_user.contacts.order(sort_column + " " + sort_direction)
    end
  end

  def new
    # @contact = current_user.contacts.build
    @contact = Contact.new
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      redirect_to @contact
    else
      render 'edit'
    end
  end

  def create
    @contact = current_user.contacts.build(contact_params)
    if @contact.save
      redirect_to @contact
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    @contact.destroy
    redirect_to contacts_path
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :address, :email, :phone)
    end

    def find_contact
      @contact = Contact.find(params[:id])
    end

    def sort_column
      %w[name].include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def portfolio
  end

  def coming_soon
  end

  def contact
  end

  def resume
  end

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_game_helper.rb
module CardGameHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def sortable(column, title=nil)
    title ||= column.titleize
    font_awesome_arrow = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {sort: column, direction: direction}, {class: font_awesome_arrow}
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/card_game/war.html.erb
<div class="modal fade modal-mini modal-primary" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header justify-content-center">
        <div class="modal-profile">
          <i class="result fa" aria-hidden="true"></i>
        </div>
      </div>
      <div class="modal-body">
        <p class="result-text"></p><br>
        <div class="card-count text-info text-center me">Your cards remaining: <span class="" id="my-card-count"></span></div>
        <hr>
        <div class="card-count text-info text-center them">Their cards remaining: <span class="" id="opp-card-count"></span></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-link btn-neutral text-center" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="page-header" filter-color="orange">
  <div class="page-header-image" style="background-image:url(<%= asset_path 'mtns.jpg' %>)"></div>
  <div class="container card-cont">
    <div class="drop-it">
      <div class="card back"></div>
      <div class="card" id="card-id-player1">
        <div class="top">
          <div class="number"></div>
          <div class="suit"></div>
        </div>
        <div class="bottom">
          <div class="number"></div>
          <div class="suit"></div>
        </div>
      </div>
      <div class="card" id="card-id-player2">
        <div class="top">
          <div class="number"></div>
          <h1 class="who">You</h1>
          <div class="suit"></div>
        </div>
        <div class="bottom">
          <div class="number"></div>
          <div class="suit"></div>
        </div>
      </div>
      <div class="card back"></div>
    </div>
  </div>
  <button class="btn btn-primary btn-round btn-lg" id="play-ball" data-toggle="modal" data-target="#myModal1">
    Play!
  </button>
</div>

app/views/contacts/_form.html.erb
<%= form_for :contact, url: contacts_path do |f| %>
  <% if @contact.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2>
        <%= pluralize(@contact.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div  class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div  class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, type: 'email', class: 'form-control' %>
  </div>

  <div  class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, type: 'number', class: 'form-control' %>
  </div>

  <footer class="text-center">
    <%= f.submit 'Submit', class: 'btn btn-outline-primary my-2 my-sm-0' %>
    <%= link_to 'Cancel', contacts_path, class: 'btn btn-outline-danger my-2 my-sm-0' %>
  </footer>
<% end %>

app/views/contacts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <div class="card card-outline-secondary">
        <div class="card-block">
          <blockquote class="card-blockquote">
            <h2 class="text-center">New Contact</h2>
            <%= render 'form' %>
          </blockquote>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="contacts-index-container">
  <div class="page-header" filter-color="orange">
    <div class="page-header-image" style="background-image:url(<%= asset_path 'contacts-index.jpg' %>)"></div>
    <div class="container contact-things">
      <div class="col-md-12">
        <div class="card">
          <ul class="nav nav-tabs nav-tabs-neutral justify-content-right" role="tablist" data-background-color="orange">
            <li class="nav-item"><h3 class="contact-index-title">Contact List</h3></li>
            <li class="nav-item">
              <a class="nav-link active" href="/contacts/new"><i class="fa fa-plus" aria-hidden="true"></i> Add Contact</a>
            </li>
          </ul>
          <div class="card-block">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <div class="card card-outline-secondary">
        <div class="card-block">
          <blockquote class="card-blockquote">
            <h2 class="text-center">New Contact</h2>
            <%= form_for :contact, url: contacts_path do |f| %>
              <div class="form-group">
                <%= f.label :name %>:<br>
                <%= f.text_field :name, class: 'form-control' %>
              </div>

              <div  class="form-group">
                <%= f.label :address %>:<br>
                <%= f.text_field :address, class: 'form-control' %>
              </div>

              <div  class="form-group">
                <%= f.label :email %>:<br>
                <%= f.text_field :email, type: 'email', class: 'form-control' %>
              </div>

              <div  class="form-group">
                <%= f.label :phone %>:<br>
                <%= f.text_field :phone, type: 'number', class: 'form-control' %>
              </div>

              <footer class="text-center">
                <%= f.submit 'Submit', class: 'btn btn-outline-primary my-2 my-sm-0' %>
              </footer>
            <% end %>
          </blockquote>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <div class="card card-outline-secondary">
        <div class="card">
          <div class="card-header">
            <%= @contact.name %>
          </div>
          <div class="card-block">
            <h4 class="card-title"><%= @contact.phone %></h4>
            <p class="card-text"><%= @contact.email %></p>
            <p class="card-text"><%= @contact.address %></p>
          </div>
          <div class="card-footer">
            <%= link_to 'Edit', edit_contact_path(@contact), class: 'btn btn-outline-primary my-2 my-sm-0' %>
            <%= link_to 'Destroy', contact_path(@contact), method: :delete, class: 'btn btn-outline-danger my-2 my-sm-0', data: { confirm: 'Are you sure?' } %>
            <%= link_to 'Back', contacts_path, class: 'btn btn-outline-info my-2 my-sm-0' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer footer-default">
  <div class="container">
    <nav>
      <ul>
        <li>
          <%= link_to "About", root_path, class: "" %>
        </li>
        <li>
          <%= link_to "Contact", static_pages_contact_path, class: "" %>
        </li>
        <li>
          <%= link_to "Resume", static_pages_resume_path, class: "" %>
        </li>
      </ul>
    </nav>
    <div class="copyright">
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md bg-primary fixed-top navbar-transparent " color-on-scroll="250">
  <div class="container">
    <div class="dropdown button-dropdown">
      <a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
        <span class="button-bar"></span>
        <span class="button-bar"></span>
        <span class="button-bar"></span>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-header menu-option">MENU</a>
        <%= link_to "About", root_path, class: "dropdown-item" %>
        <%= link_to "Contact", static_pages_contact_path, class: "dropdown-item" %>
        <%= link_to "Resume", static_pages_resume_path, class: "dropdown-item" %>
        <% if user_signed_in? %>
          <div class="dropdown-divider"></div>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        <% else %>
          <div class="dropdown-divider"></div>
          <%= link_to "Sign In", user_session_path, class: "dropdown-item" %>
        <% end %>
      </div>
    </div>
    <div class="navbar-translate">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-bar bar1"></span>
        <span class="navbar-toggler-bar bar2"></span>
        <span class="navbar-toggler-bar bar3"></span>
      </button>
      <a class="navbar-brand" href="/">
        Jon Lambson
      </a>
    </div>
    <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="">
      <ul class="navbar-nav">
        <div class="hide-menu">
          <li class="nav-item">
            <%= link_to "About", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", static_pages_contact_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Resume", static_pages_resume_path, class: "nav-link" %>
          </li>
          <hr class="line-divide">
        </div>
        <li class="nav-item">
          <a class="nav-link" rel="tooltip" title="Follow me on Twitter" data-placement="bottom" href="https://twitter.com/jonlambsonite" target="_blank">
            <i class="fa fa-twitter"></i>
            <p class="hidden-lg-up">Twitter</p>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" rel="tooltip" title="Like me on Facebook" data-placement="bottom" href="https://www.facebook.com/jon.lambson" target="_blank">
            <i class="fa fa-facebook-square"></i>
            <p class="hidden-lg-up">Facebook</p>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" rel="tooltip" title="Follow me on Instagram" data-placement="bottom" href="https://www.instagram.com/jon.lambsonite/" target="_blank">
            <i class="fa fa-instagram"></i>
            <p class="hidden-lg-up">Instagram</p>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" rel="tooltip" title="Look at my Github" data-placement="bottom" href="https://github.com/jonthedecepticon" target="_blank">
            <i class="fa fa-github-alt" aria-hidden="true"></i>
            <p class="hidden-lg-up">Github</p>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<% flash.each do |message_type, message| %>
  <div class="remove-alert">
    <% if message_type == "alert" %>
      <div class="alert alert-danger" role="alert">
        <div class="container">
          <div class="alert-icon">
          </div>
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">
              <i class="fa fa-times close-alert" aria-hidden="true"></i>
            </span>
          </button>
        </div>
      </div>
    <% else %>
      <div class="alert alert-success" role="alert">
        <div class="container">
          <div class="alert-icon">
          </div>
          </strong> <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">
              <i class="fa fa-times close-alert" aria-hidden="true"></i>
            </span>
          </button>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <title>Jon Lambson</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Grand+Hotel' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/4f6a4b08efdad6bb29f9cc801f5c07e263b39907/devicon.min.css">
  </head>

  <body class="<%= request.path_info.gsub('/','-') %>">
    <%= render 'layouts/header' %>
    <%= render 'layouts/notifications' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/coming_soon.html.erb
<iframe id="player" type="text/html" width="100%" height="100%"
  src="https://www.youtube.com/embed/8Ow9eHdw11w?autoplay=1"
  frameborder="0"></iframe>

<div class="coming-soon-container">
  <div class="hit-the-floor">Coming Soon...</div>
  <div class="hit-the-floor-small">Sorry, I'm still currently building out this functionality. Check back soon! <br>
    But in the mean time, watch this cool video!
  </div>
</div>

<style media="screen">
  html {
    height: 100%;
  }
  .-static_pages-coming_soon {
    height: 100%;
  }
  nav.navbar.navbar-toggleable-md.bg-primary.fixed-top.navbar-transparent {
    background-color: black !important;
  }
  footer.footer.footer-default {
    background-color: black;
    margin-top: -10px !important;
  }
  footer.footer.footer-default a {
    color: white;
  }
  .hit-the-floor {
    color: #fff;
    font-size: 12em;
    font-weight: bold;
    font-family: Helvetica;
    text-shadow: 0 1px 0 #ccc, 0 2px 0 #c9c9c9, 0 3px 0 #bbb, 0 4px 0 #b9b9b9, 0 5px 0 #aaa, 0 6px 1px rgba(0,0,0,.1), 0 0 5px rgba(0,0,0,.1), 0 1px 3px rgba(0,0,0,.3), 0 3px 5px rgba(0,0,0,.2), 0 5px 10px rgba(0,0,0,.25), 0 10px 10px rgba(0,0,0,.2), 0 20px 20px rgba(0,0,0,.15);
  }
  .hit-the-floor {
    text-align: center;
  }
  .hit-the-floor-small {
    color: #fff;
    font-size: 2em;
    font-weight: bold;
    font-family: Helvetica;
    text-shadow: 0 1px 0 #ccc, 0 2px 0 #c9c9c9, 0 3px 0 #bbb, 0 4px 0 #b9b9b9, 0 5px 0 #aaa, 0 6px 1px rgba(0,0,0,.1), 0 0 5px rgba(0,0,0,.1), 0 1px 3px rgba(0,0,0,.3), 0 3px 5px rgba(0,0,0,.2), 0 5px 10px rgba(0,0,0,.25), 0 10px 10px rgba(0,0,0,.2), 0 20px 20px rgba(0,0,0,.15);
  }
  .hit-the-floor-small {
    text-align: center;
  }
  body {
    background-color: #f1f1f1;
  }
  .coming-soon-container {
    padding-top: 200px;
    height: 750px;
    position: absolute;
    padding-left: 75px;
  }
  iframe#player {
    position: absolute;
  }
</style>

app/views/static_pages/contact.html.erb
<div class="page-header" filter-color="orange">
  <div class="page-header-image" style="background-image:url(<%= asset_path 'bg8.jpg' %>)"></div>
  <div class="container">
    <div class="col-md-4 content-center">
      <div class="card card-login card-plain">
        <div class="section section-contact-us text-center">
          <div class="container">
            <h2 class="title">Want to work with me?</h2>
            <p class="description">Just shoot me a message.</p>
            <div class="row">
              <div class="col-lg-6 text-center offset-lg-3 col-md-8 offset-md-2">
                <div class="input-group form-group-no-border input-lg">
                  <input type="text" class="form-control" placeholder="First Name...">
                </div>
                <div class="input-group form-group-no-border input-lg">
                  <input type="text" class="form-control" placeholder="Email...">
                </div>
                <div class="textarea-container">
                  <textarea class="form-control" name="name" rows="4" cols="80" placeholder="Type a message..."></textarea>
                </div>
                <div class="send-button">
                  <a href="/static_pages/coming_soon" class="btn btn-primary btn-round btn-block btn-lg">Send Message</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="profile-page">
  <div class="wrapper">
    <div class="page-header page-header-small" filter-color="orange">
      <div class="page-header-image" data-parallax="true" style="background-image: url(<%= asset_path 'home-hero-img.jpg' %>);">
      </div>
      <div class="container">
        <div class="content-center">
          <div class="photo-container">
            <%= image_tag "me.jpg", class: "rounded-circle img-raised" %>
          </div>
          <h3 class="title">Jon Lambson</h3>
          <p class="category">Jr. Software Developer</p>
          <div class="content">
            <div class="social-description">
            </div>
            <div class="social-description">
            </div>
            <div class="social-description">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="section bg-grad">
      <div class="container">
        <div class="button-container">
          <a href="" class="btn btn-default btn-round btn-lg btn-icon no-click">
            <i class="devicon-javascript-plain"></i>
          </a>
          <a href="" class="btn btn-default btn-round btn-lg btn-icon no-click">
            <i class="devicon-jquery-plain"></i>
          </a>
          <a href="" class="btn btn-default btn-round btn-lg btn-icon no-click">
            <i class="devicon-react-original"></i>
          </a>
          <a href="" class="btn btn-default btn-round btn-lg btn-icon no-click">
            <i class="devicon-ruby-plain"></i>
          </a>
          <a href="" class="btn btn-default btn-round btn-lg btn-icon no-click">
            <i class="devicon-rails-plain"></i>
          </a>
          <a href="" class="btn btn-default btn-round btn-lg btn-icon no-click">
            <i class="devicon-angularjs-plain"></i>
          </a>
          <a href="" class="btn btn-default btn-round btn-lg btn-icon no-click">
            <i class="devicon-photoshop-line"></i>
          </a>
          <a href="/static_pages/resume" class="btn btn-primary btn-round btn-lg" rel="tooltip" title="Checkout My Resume">Skills</a>
          <a href="" class="btn btn-default btn-round btn-lg btn-icon no-click">
            <i class="devicon-illustrator-line"></i>
          </a>
          <a href="" class="btn btn-default btn-round btn-lg btn-icon no-click">
            <i class="devicon-github-plain"></i>
          </a>
          <a href="" class="btn btn-default btn-round btn-lg btn-icon no-click">
            <i class="devicon-bootstrap-plain"></i>
          </a>
          <a href="" class="btn btn-default btn-round btn-lg btn-icon no-click">
            <i class="devicon-atom-original"></i>
          </a>
          <a href="" class="btn btn-default btn-round btn-lg btn-icon no-click">
            <i class="devicon-nodejs-plain"></i>
          </a>
          <a href="" class="btn btn-default btn-round btn-lg btn-icon no-click">
            <i class="devicon-mongodb-plain"></i>
          </a>
          <a href="" class="btn btn-default btn-round btn-lg btn-icon no-click">
            <i class="devicon-postgresql-plain"></i>
          </a>
        </div>
        <div class="move-down">
          <h3 class="title">About me</h3>
          <h5 class="description">
            <p>Distinctio nonummy, ultrices? Consectetuer, quibusdam lacinia tristique etiam? Culpa minus omnis totam excepteur eu cillum? Ratione vel, hac impedit ipsum maxime reiciendis? Minima ex curabitur.</p>
            <p>Distinctio nonummy, ultrices? Consectetuer, quibusdam lacinia tristique etiam? Culpa minus omnis totam excepteur eu cillum? Ratione vel, hac impedit ipsum maxime reiciendis? Minima ex curabitur.</p>
          </h5>
        </div>
        <div class="row">
          <div class="col-md-6 offset-md-3 panetab">
            <h4 class="title text-center">My Portfolio</h4>
            <div class="nav-align-center">
              <ul class="nav nav-pills nav-pills-primary" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" data-toggle="tab" href="#page1" role="tablist">
                    <i class="fa fa-newspaper-o" aria-hidden="true"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="tab-content gallery">
            <div class="tab-pane active" id="page1" role="tabpanel">
              <div class="row">
                <div class="col-md-12 offset-md-2 move-left">
                  <div class="row collections">
                    <div class="col-md-6 side-projects-2by2">
                      <a href="/404-page">
                        <div class="box">
                          <%= image_tag "404.png", class: "img-raised 404-img" %>
                          <span class="caption fade-caption">
                          <h3 class="text-center text-primary">404 Page</h3>
                          <p>Not a side project, just wanted to play around with the 404 page...</p>
                          <p class="text-info">Built with Ruby/Rails/JavaScript</p>
                          </span>
                        </div>
                      </a>
                      <p class="text-center mobile-sd-title"><a href="/static_pages/coming_soon" class="btn btn-link btn-info">Side Project #1</a></p>
                      <a href="/contacts">
                        <div class="box">
                          <%= image_tag "contact.jpg", class: "img-raised" %>
                          <span class="caption fade-caption">
                          <h3 class="text-center text-primary">Address Book</h3>
                          <p>PostgreSQL as the database system. Ability to add, edit, and delete contacts. Ability to view all contacts in a list sorted alphabetically by name...</p>
                          <p class="text-info">Built with Ruby on Rails</p>
                          </span>
                        </div>
                      </a>
                      <p class="text-center mobile-sd-title"><a href="/static_pages/coming_soon" class="btn btn-link btn-info">Side Project #3</a></p>
                    </div>
                    <div class="col-md-6 side-projects-2by2">
                      <a href="/card_game/war">
                        <div class="box">
                          <%= image_tag "cards.jpg", class: "img-raised" %>
                          <span class="caption fade-caption">
                          <h3 class="text-center text-primary">War - Card Game</h3>
                          <p>The deck is divided evenly, with each player receiving 26 cards, dealt one at a time, face down. Anyone may deal first. Each player places his stack of cards face down, in front of him...</p>
                          <p class="text-info">Built with JavaScript</p>
                          </span>
                        </div>
                      </a>
                      <p class="text-center mobile-sd-title"><a href="/static_pages/coming_soon" class="btn btn-link btn-info">War - Card Game</a></p>
                      <a href="/static_pages/coming_soon">
                        <div class="box">
                          <%= image_tag "bg7.jpg", class: "img-raised" %>
                          <span class="caption fade-caption">
                          <h3 class="text-center text-primary">Side Project #4</h3>
                          <p>This will be a brief description of what the side project is...</p>
                          <p class="text-info">Built with JavaScript</p>
                          </span>
                        </div>
                      </a>
                      <p class="text-center mobile-sd-title"><a href="/static_pages/coming_soon" class="btn btn-link btn-info">Side Project #4</a></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/portfolio.html.erb
<h1>StaticPages#portfolio</h1>
<p>Find me in app/views/static_pages/portfolio.html.erb</p>

app/views/static_pages/resume.html.erb
<div class="page-header" filter-color="orange">
  <div class="page-header-image" style="background-image:url(<%= asset_path 'bg7.jpg' %>)"></div>
  <div class="container">
    <div class="res-container">
      <%= image_tag "resume.png", class: "img-raised" %>
    </div>
  </div>
</div>